In [18]:
from keras.models  import load_model
from keras.preprocessing import image
import numpy as np

In [19]:
model = load_model("breastcancer.h5")

In [20]:
img = image.load_img('benign.png',target_size = (64,64))

In [21]:
x  = image.img_to_array(img)
x = np.expand_dims(x,axis = 0)

In [6]:
pred = model.predict_classes(x)

AttributeError: 'Sequential' object has no attribute 'predict_classes'

In [11]:
pred

array([[1]])

In [5]:
pred=model.predict(x)

In [6]:
pred

array([[1.]], dtype=float32)

In [10]:
pred[0][0]

1.0

In [9]:
pr=np.argmax(model.predict(x),axis=-1)

In [10]:
pr

array([0], dtype=int64)

In [22]:
c=np.argmax(model.predict(x),axis=-1)

In [23]:
if c==0:
    print('no')

no
